services:
  - type: web
    name: hyperliquid-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools==68.2.2
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your-bot-token
      - key: ADMIN_CHAT_ID
        value: "1234567890"
